// Example of code generated by @aws-cdk/lazify

Object.defineProperty(exports, "__esModule", { value: !0 });
Object.defineProperty(exports, "Bar", { value: "Bar" });

var _noFold;
(exports.Foo = void 0),
  Object.defineProperty(exports, (_noFold = "Foo"), {
    enumerable: !0,
    configurable: !0,
    get: () => {
      console.trace("core Foo getter called")
      return 1
    },
  });
